language: java
jdk:
  - oraclejdk8
before_script:
  - chmod +x gradlew
script:
  - chmod +x gradlew
  - ./gradlew check
  - ./gradlew jacocoTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)